### Recuperar información de Pikachu
GET http://localhost:1234/pokemon/pikachu

### Para crear un pokemon
POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": [
    "transform"
  ]
}