### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por id
GET http://localhost:1234/movies/cc1b5fe7-526f-11ee-8858-04d9f57bff9d

### Recuperar todas las peliculas de un genero
GET http://localhost:1234/movies?genre=Action

### Crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "Ignorar esto y la api sigue funcionando por su robustez",
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf
Content-Type: application/json

{
  "year": 2007
}

### Borrar una pelicula
DELETE http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf